### ISSUE TITLE
Still no sound on ryzen 5 5500U :(

### ISSUE THREAD

**Issue by ghost** [codepayne/linux-sound-huawei#1]
I compiled this kernel, installed modules, bzImage and generated initramfs. It boots up successfully.
I see Renoir Radeon High Definition Audio Controller in pavucontrol, however it produces no sounds through speakers or headphone jack. Bluetooth is working, but it was working on mainline kernel too.

I blacklisted modules snd_pci_acp5x and snd_rn_pci_acp3x as it was recommended in https://github.com/thesofproject/linux/issues/3249, but still got no success after reboot.

What info can I provide to help with debugging further? 

here's lsmod | grep snd_ :

```
[user@laptop ~]$ lsmod | grep snd_
snd_seq_dummy          16384  0
snd_hrtimer            16384  1
snd_acp3x_i2s          16384  0
snd_acp3x_pcm_dma      16384  0
snd_sof_amd_rembrandt    16384  0
snd_sof_amd_renoir     16384  0
snd_sof_amd_acp        40960  2 snd_sof_amd_rembrandt,snd_sof_amd_renoir
snd_sof_pci            24576  2 snd_sof_amd_rembrandt,snd_sof_amd_renoir
snd_hda_codec_hdmi     77824  1
snd_sof               233472  2 snd_sof_amd_acp,snd_sof_pci
snd_hda_intel          49152  3
snd_sof_utils          20480  1 snd_sof
snd_intel_dspcfg       32768  2 snd_hda_intel,snd_sof
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_pci_ps             20480  0
snd_soc_es8316         49152  0
snd_rpl_pci_acp6x      20480  0
snd_soc_core          290816  4 snd_acp3x_pcm_dma,snd_acp3x_i2s,snd_sof,snd_soc_es8316
snd_hda_codec         143360  2 snd_hda_codec_hdmi,snd_hda_intel
snd_acp_pci            16384  0
snd_acp_config         16384  3 snd_sof_amd_rembrandt,snd_acp_pci,snd_sof_amd_renoir
snd_hda_core           94208  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
snd_compress           28672  1 snd_soc_core
snd_soc_acpi           16384  2 snd_sof_amd_acp,snd_acp_config
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pci_acp6x          20480  0
snd_hwdep              16384  1 snd_hda_codec
ac97_bus               16384  1 snd_soc_core
snd_pci_acp3x          20480  0
snd_pcm               135168  16 snd_acp3x_pcm_dma,snd_sof_amd_acp,snd_hda_codec_hdmi,snd_pci_acp6x,snd_hda_intel,snd_hda_codec,snd_sof,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_es8316,snd_hda_core,snd_pci_ps,snd_pcm_dmaengine
snd_seq                90112  7 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
snd_timer              45056  3 snd_seq,snd_hrtimer,snd_pcm
snd                   102400  17 snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm
```

**Comment by codepayne** [comment]
Hi,

Did you contact me by email? I need information about your hardware to make the driver work. Check the instructions in 
https://bugzilla.kernel.org/show_bug.cgi?id=215119#c35

**Comment by ghost** [comment]
No, I couldn't find your address. Here's requested info:
https://pastebin.com/dp1Qc4eK - cat /proc/cpuinfo
https://pastebin.com/Awp8BpWF - sudo dmidecode
https://pastebin.com/dcd0NFqj - cat /sys/class/dmi/id/modalias
[acpidump.zip](https://github.com/codepayne/linux-sound-huawei/files/10387088/acpidump.zip)

laptop is huawei matebook 14, KLVL-WXXW M1010

**Comment by codepayne** [comment]
Your laptop should be supported, follow the instructions at https://github.com/thesofproject/linux/issues/3249#issuecomment-1378025039

**Comment by ghost** [comment]
redid everything from scratch, added blacklisted modules, and it worked. thanks, you are the legend!
