### ISSUE TITLE
kernel 6.1.3

### ISSUE THREAD

**Issue by stafuz** [codepayne/linux-sound-huawei#10]
It makes no sens to compile the kernel patch with version 6.1.3 since the are a lot of bugs in 6.1.3. why we are not using 6.1.9 wich is more stable and has not suspend and resume errors?

**Comment by codepayne** [comment]
because when I created this repository, 6.1.3 was the latest stable kernel from gkh. Are you 100% sure, that these suspend/resume issues are fixed in 6.1.9?

**Comment by Alexey336** [comment]
Mine MateBook 14 can't suspend on any 6.1.X kernel, even on 6.1.9. Just checked today 
It instantly awakes seconds after suspending

**Comment by stafuz** [comment]
I have compiled the patch with kernel 6.2.rc6 and the suspend/resume errors have gone. Laptop is working fine. There have been corrections in the i2c dirvers. Check changelog in kernel.org!

**Comment by codepayne** [comment]
> I have compiled the patch with kernel 6.2.rc6 and the suspend/resume errors have gone. Laptop is working fine. 

Great, but it is a mainline kernel which is more dangerous to run. It could cause filesystem corruptions which are more damaging then any suspend/resume issues. I do not want to offer the mainline kernel.

If you want, you can investigate which **stable** kernel version works ok with suspend/resume and I will try to port the driver to that version. It could be also an older than 6.1.3 kernel version.

**Comment by nick8325** [comment]
In case it helps anyone else, suspend works for me after running the following command: `echo disabled > /sys/bus/i2c/devices/i2c-ESSX8336:00/power/wakeup`

**Comment by Alexey336** [comment]
> In case it helps anyone else, suspend works for me after running the following command: `echo disabled > /sys/bus/i2c/devices/i2c-ESSX8336:00/power/wakeup`

It helped thanks!

**Comment by ghost** [comment]
Stable kernel reached 6.2.9, have somebody checked it with these patches?
