### ISSUE TITLE
Headset makes sound driver crash

### ISSUE THREAD

**Issue by stafuz** [codepayne/linux-sound-huawei#11]
After resume from suspend with headset pluged in sound driver crashes. Only a reboot can restore the sound.

**Comment by Alexey336** [comment]
This problem is outlined in the wiki 

https://github.com/codepayne/linux-sound-huawei/wiki

**Comment by stafuz** [comment]
And so we let it this way or we solve it?

**Comment by codepayne** [comment]
@stafuz 
Again, there is no "we" here, until this point in time, there was just me. 

If you have a solution for this problem, you can create a pull request and I will take a look at it. 
For the moment I don't consider this problem as a severe limitation (same as the internal mic), so I won't work on it. Right now I'm focusing on preparing the driver for upstreaming (where I'll probably try to fix this issue too), which would be more beneficial.
