### ISSUE TITLE
CPU Performance Scaling Driver

### ISSUE THREAD

**Issue by Alexey336** [codepayne/linux-sound-huawei#13]
Somehow there is acpi-cpufreq enabled by default in this kernel instead of more efficient amd-pstate (or maybe it's my fault while building?)

Anyway maybe we can add some info about it in Wiki?

I enabled amd-pstate with "amd_pstate=passive" argument in grub and blacklisting acpi-cpufreq in /etc/modprobe.d/blacklist.conf

**Comment by codepayne** [comment]
@Alexey336 If you like you can test my new sound driver here:
 https://github.com/codepayne/pop-os-linux/wiki

Be aware, that the MICs do not work properly there, but the suspend and cpufreq driver should be running ok.

**Comment by Alexey336** [comment]
> @Alexey336 If you like you can test my new sound driver here: https://github.com/codepayne/pop-os-linux/wiki

Sure, I will test it as soon as possible. Does this kernel compatiable with other distros? I'm using Fedora 37

**Comment by codepayne** [comment]
@Alexey336 The internet says that fedora 37 came with kernel 6.0, the kernek that I posted is 6.0.12 so from this aspect they should be compatible. But I don't use fedora so I can't say for sure. You could use your fedora kernel config when building the kernel just make sure that the kernel options mentioned in the wiki are enabled.

**Comment by Alexey336** [comment]
Finally found some time to try out a new version of the kernel. I did everything exactly according to the instructions, even using .config from your repository and not the Fedora kernel. The problem with amd_pstate has been solved, I specifically removed my fixes from blacklist and grub for this. The sound from the headphones is excellent, though I can't compare it with the previous kernel, because I used a USB sound card. The microphone of the headphones works (I'm using earpods), but there are some noises in the background. This is not the case with a usb sound card, so I prefer to use it further. The laptop microphone only records noises, but I've never used it anyway. 

As for the sound from the laptop speakers, I had to increase the Headphone parameter in alsamixer to return to normal volume

Sorry for writing in this topic, there is no Issues section in your pop os kernel fork repository and many thanks for your work! 

![image](https://user-images.githubusercontent.com/9166661/224496499-0545dc71-72f5-411c-8b53-2778dafbc627.png)

**Comment by codepayne** [comment]
@Alexey336 Thanks for the hint, forgot to activate issues in the other repo, now  it's activated.  
The noise of the microphone could be caused by the capture settings in alsamixer, some knob may be turned too high, I myself don't really understand what most of these knobs do. You should experiment with them, you may be able to lower the noise.
