### ISSUE TITLE
Loading Linux <version> stuck

### ISSUE THREAD

**Issue by laricko** [codepayne/linux-sound-huawei#14]
What I did:
- `make defconfig` because others scripts were too much questions. Idk what I need to answer
- `make`
- copy bzImage (tried 86 and 86_64) to boot with name vmlinuz-SOUND_HERE

And when I choosed this kernel I got `Loading Linux SOUND_HERE ...`

My sistem:
HUAWEI 14 AMD Ryzen 5 5500U

What is wrong? I need make proper config?

**Comment by codepayne** [comment]
@laricko You can try the kernel from here:
https://github.com/codepayne/pop-os-linux/wiki

It has a working config file if that is your problem.
