### ISSUE TITLE
Problem with suspend

### ISSUE THREAD

**Issue by thekirici** [codepayne/linux-sound-huawei#17]
First of all, I successfully configured the kernel and alsamixer settings and the sound is working perfectly. Thank you for solving this problem.
But the problem is that when I suspend the computer or close the laptop screen, it continues to consume power. In lock mode, the screen light turns on every 1 minute. In suspend mode, it wakes up instantly. And I see the login screen. Last night I just lowered my screen with 80% charge, and when I woke up, it was 0%.

I don't understand if this is caused by audio driver or the kernel itself. It feels like when I suspend, the speaker is not disabled, it works and causing the computer to wake up immediately after the suspension.
Is there any way to solve this problem?

**Comment by codepayne** [comment]
This is caused by some regression in the newer kernels, I have released a new version of the sound driver with an older kernel version, that should have this issue fixed:
https://github.com/codepayne/pop-os-linux/wiki
