### ISSUE TITLE
HUAWEI MateBook D16 (AMD) HVY-WXX9 M1020, no sound

### ISSUE THREAD

**Issue by KTGJ** [codepayne/linux-sound-huawei#18]
Hi. I tried to build this kernel for my laptop. amd-acp3x-essx8336 appeared in alsamixer only after I changed in "sound/soc/amd/acp3x-es8336.c" M1040 to M1020:

```
{
	.matches = {
		DMI_EXACT_MATCH(DMI_BOARD_VENDOR, "HUAWEI"),
		DMI_EXACT_MATCH(DMI_PRODUCT_NAME, "HVY-WXX9"),
		DMI_EXACT_MATCH(DMI_PRODUCT_VERSION, "M1020"),
	},
	.driver_data = &acp3x_es8336,
},
```

After that I booted the new kernel, switched in alsamixer to amd-acp3x-essx8336 and adjusted the settings alsamixer according to the instructions. However, there is still no sound...

[dmidecode](https://github.com/codepayne/linux-sound-huawei/files/10998577/dmidecode.txt)

[dmesg](https://github.com/codepayne/linux-sound-huawei/files/10998583/dmesg.txt)

[lspci](https://github.com/codepayne/linux-sound-huawei/files/10998598/lspci.txt)

[lsmod](https://github.com/codepayne/linux-sound-huawei/files/10998617/lsmod.txt)

<details>
<summary>Alsamixer settings</summary>

![1](https://user-images.githubusercontent.com/58131462/225828916-4bdcb6c6-9b3a-451b-9b29-e08d0f28d7a7.jpg)
</details>

**Comment by codepayne** [comment]
@KTGJ I looked at your logs and alsamixer settings, nothing seems wrong, I can't say why it isn't working for you. You seem to have a laptop version I didn't encounter before, so maybe you have some differences in HW.
I recommend you to try the kernel from here and follow the wiki: https://github.com/codepayne/pop-os-linux/wiki

If it still doesn't work, open an issue there.

**Comment by KTGJ** [comment]
I think I figured out what the problem was... After I set "LDATA TO LDAC, RDATA TO RDAC" in "DAC Source Mux", the sound appeared. Thank you. And yes, on my laptop I still need to change M1040 to M1020 in "sound/soc/amd/acp3x-es8336.c", otherwise nothing appears in alsamixer.

![2](https://user-images.githubusercontent.com/58131462/226152676-d0215554-32aa-49b2-b2b9-6e9d285c9b4b.jpg)

**Comment by badriev** [comment]
@KTGJ 
Hello. Do jack headphones with microphone work after the fix?
