### ISSUE TITLE
No new sound card in alsamixer (Matebook 14 AMD Ryzen 5500U)

### ISSUE THREAD

**Issue by mvnh** [codepayne/linux-sound-huawei#19]
Did everything as described in the wiki, but the new soundcard didnt apper in alsamixer.
dmesg:
[dmesg.txt](https://github.com/codepayne/linux-sound-huawei/files/11185930/dmesg.txt)

**Comment by codepayne** [comment]
Since you didn't attach the output of lsmod I can't tell for sure, but it looks like the proper sound driver wasn't loaded.
Can't say why without additional information

**Comment by MRC-Hg** [comment]
hello, I also don’t have new sound cards in my devices, I tried building and running different kernels (linux-6.4.12+patch linux-sound-huawei pop-os-linux) now I have pop-os-linux running

<details><summary>my lsmod is:</summary>
<p>
```c
Module Size Used by
...
...
snd_sof_amd_rembrandt 16384 0

snd_sof_amd_renoir 16384 0

snd_sof_amd_acp 45056 2 snd_sof_amd_rembrandt,snd_sof_amd_renoir
snd_sof_pci 24576 2 snd_sof_amd_rembrandt,snd_sof_amd_renoir

snd_sof_xtensa_dsp 16384 1 snd_sof_amd_acp

snd_sof 311296 2 snd_sof_amd_acp,snd_sof_pci

snd_hda_codec_hdmi 94208 1
snd_sof_utils 20480 1 snd_sof

snd_hda_intel 61440 1
huawei_wmi 20480 0

snd_intel_dspcfg 36864 2 snd_hda_intel,snd_sof
snd_rpl_pci_acp6x 20480 0

snd_acp_pci 16384 0
snd_intel_sdw_acpi 20480 1 snd_intel_dspcfg

snd_acp_config 16384 3 snd_sof_amd_rembrandt,snd_acp_pci,snd_sof_amd_renoir
snd_hda_codec 204800 2 snd_hda_codec_hdmi,snd_hda_intel

snd_soc_acpi 16384 2 snd_sof_amd_acp,snd_acp_config
snd_hda_core 135168 3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
snd_pci_acp6x 20480 0

snd_hwdep 20480 1 snd_hda_codec

snd_pci_acp3x 20480 0
snd_acp3x_i2s 16384 0
snd_acp3x_pcm_dma 16384 0
snd_soc_es8316 53248 0
snd_soc_core 417792 4 snd_acp3x_pcm_dma,snd_acp3x_i2s,snd_sof,snd_soc_es8316
snd_compress 28672 1 snd_soc_core
ac97_bus 16384 1 snd_soc_core
snd_pcm_dmaengine 20480 1 snd_soc_core
snd_pcm 192512 14 snd_acp3x_pcm_dma,snd_sof_amd_acp,snd_hda_codec_hdmi,snd_pci_acp6x,snd_hda_intel,snd_hda_codec,snd_sof,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_es8316,snd_hda_core,snd_pci_ps,snd_pcm_dmaengine
snd_seq_midi 20480 0
snd_seq_midi_event 16384 1 snd_seq_midi
snd_rawmidi 53248 1 snd_seq_midi
snd_seq 94208 2 snd_seq_midi,snd_seq_midi_event
snd_seq_device 16384 3 snd_seq,snd_seq_midi,snd_rawmidi
snd_timer 49152 2 snd_seq,snd_pcm
snd 135168 14 snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi
soundcore 16384 1 snd

...
...

```
</p>
</details> 

<details><summary>System is</summary>
<p>
``
AMD Ryzen 5 4600H with Radeon Graphics
HVY-WXX9
M1010
``
</p>
</details>

**Comment by codepayne** [comment]
Did you follow the wiki?
https://github.com/codepayne/linux-sound-huawei/wiki

**Comment by MRC-Hg** [comment]
> Did you follow the wiki? https://github.com/codepayne/linux-sound-huawei/wiki

yes ! ((

**Comment by mvnh** [comment]
> Since you didn't attach the output of lsmod I can't tell for sure, but it looks like the proper sound driver wasn't loaded.
> Can't say why without additional information

Thanks for the reply, but it's been 7 months now and I'm not even using a Linux distro :)

**Comment by MRC-Hg** [comment]
I coment modules from /etc/modprobe.d/blacklist.conf and /etc/modules-load.d/modules.conf

cat /proc/asound/cards     
 0 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xd03c0000 irq 87
 1 [acp            ]: acp - acp
                      HUAWEI-HVY_WXX9-M1010-HVY_WXX9_PCB_B1

INTEL -?!?!

**Comment by codepayne** [comment]
@MRC-Hg I don't see the driver snd_soc_acp3x_es8336_mach in your lsmod output. It must be loaded for the sound to work. Paste the contents of /etc/modprobe.d/blacklist.conf and /etc/modules-load.d/modules.conf

**Comment by MRC-Hg** [comment]
hi bro, thanks for the answer, Today I built a kernel with sound card support, with changing some settings in alasmixer I can hear the sound, thanks to you and other people helping in this project
