### ISSUE TITLE
dummy sound setup due to a missing module in the core on a huawei mate d15 laptop.

### ISSUE THREAD

**Issue by saber716rus** [codepayne/linux-sound-huawei#21]
hello. I use green-linux - it's a fork of linux mint, with a mainline core from amd. huawei mate d15 laptop.
raised a question in the xanmod core gitlab.
https://gitlab.com/xanmod/linux/-/issues/380

System:
  Kernel: 6.4.5-x64v1-xanmod1 x86_64 bits: 64 compiler: gcc v: 12.3.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: HUAWEI product: BOM-WXX9 v: M1010 serial: <superuser required>
  Mobo: HUAWEI model: BOM-WXX9-PCB-B2 v: M1010 serial: <superuser required> UEFI: HUAWEI v: 2.12
    date: 03/16/2023

Audio:
  Device-1: AMD Renoir Radeon High Definition Audio vendor: QUANTA driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 03:00.1 chip-ID: 1002:1637
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor vendor: QUANTA
    driver: snd_rn_pci_acp3x v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 03:00.5
    chip-ID: 1022:15e2
  Sound Server-1: ALSA v: k6.4.5-x64v1-xanmod1 running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes

**Comment by codepayne** [comment]
I don't understand what you are reporting here, I don't see the issue you're having

**Comment by saber716rus** [comment]
> I don't understand what you are reporting here, I don't see the issue you're having

However, the problem still exists. Otherwise I wouldn't have written about her. More precisely, alsa sees only a dummy sound, although pulseaudio detects the map, but there is also no sound. laptop model BOM-WXX9-PCB-B2

**Comment by codepayne** [comment]
What does "dummy sound setup due to a missing module in the core" is supposed to tell me?
What is a "core" ? What module is missing? Why should it be in the "core"?
Why didn't you attach a kernel buffer output? This is the first step in analyzing any kernel issue.
You should have explained the issue you're having in more detail.

**Comment by saber716rus** [comment]
In the 6th version of the kernel, it is present - this is the es8316 module, but unfortunately it apparently does not work correctly or perhaps the topology is not enough.

**Comment by saber716rus** [comment]
saber716rus@BOM-WXX9 ~> lsmod | grep es8316
snd_soc_es8316         53248  0
snd_soc_core          348160  4 
snd_acp3x_rn,snd_soc_es8316,snd_soc_dmic,snd_acp3x_pdm_dma
snd_pcm               159744  9 
snd_hda_codec_hdmi,snd_pci_acp6x,snd_hda_intel,snd_hda_codec,snd_compress,snd_soc_core,snd_soc_es8316,snd_hda_core,snd_acp3x_pdm_dma
saber716rus@BOM-WXX9 ~>

**Comment by saber716rus** [comment]
https://linux-hardware.org/?probe=3a547e1959

**Comment by codepayne** [comment]
Why are you interested in the es8316 driver? 
This driver will not give you sound, it is a codec driver for your hardware codec. You also need a machine driver
that ties the CPU ACP controller to the codec. This is what my driver is doing.
You are not using my driver since I don't see it in the lsmod output.

If you want to use my driver you have to follow the instructions in the wiki:
https://github.com/codepayne/linux-sound-huawei/wiki

**Comment by saber716rus** [comment]
Because my laptop uses it. I did, but there is still no sound, but there is a positive result, the sound card saw alsa and more profiles appeared in pulseaudio. I made lsmod in a new way
[lsmod.txt](https://github.com/codepayne/linux-sound-huawei/files/13198999/lsmod.txt)

![Снимок экрана от 2023-10-29 22-16-17](https://github.com/codepayne/linux-sound-huawei/assets/22714555/fb5887e9-7837-496b-b2c2-acc37b4b4743)

**Comment by codepayne** [comment]
As I told you es8316 will not make your speakers work, it's just a CODEC driver. That is not enough to have working sound.
Did you follow the wiki? Why didn't you attach kernel logs?

**Comment by saber716rus** [comment]
[dmesg.txt](https://github.com/codepayne/linux-sound-huawei/files/13199046/dmesg.txt)
I apologize. Yes, I understand that this is just a small part of what can start the sound on my device.

**Comment by saber716rus** [comment]
saber716rus@BOM-WXX9 ~> uname -a
Linux BOM-WXX9 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
saber716rus@BOM-WXX9 ~>

**Comment by codepayne** [comment]
Did you follow the wiki?

**Comment by saber716rus** [comment]
> Did you follow the wiki?

Yes, I'm watching.

**Comment by saber716rus** [comment]
> Did you follow the wiki?

Yes, I'm watching.

**Comment by codepayne** [comment]
> > Did you follow the wiki?
> 
> Yes, I'm watching.

Do not watch the wiki, FOLLOW the instructions inside.
