### ISSUE TITLE
I dont know how build it and cant find info in internet. Can you please provide plan to build and install ?

### ISSUE THREAD

**Issue by devops-engineer-gaming** [codepayne/linux-sound-huawei#22]
Its very important for me, sound is only one problem on my huawei linux desktop and i dont wanna sell my laptop (

**Comment by codepayne** [comment]
The driver will be eventually part of the official kernel in the future, but it is hard to say when it will reach the linux distros. Could take some time. It would be very time consuming to teach you how to compile your own kernel, and I very much doubt that there is no info on the internet how to compile a linux kernel.
