### ISSUE TITLE
No sound after configuring alsamixer on BOM-WXX9 M1010

### ISSUE THREAD

**Issue by accelolabs** [codepayne/linux-sound-huawei#25]
I compiled kernel from special branch with needed parameters, made changes to configuration files and configured alsamixer according to the wiki, but there is still no sound for some reason. Alsamixer is displaying soundcard, but system doesn't display it in graphical interface.

Here is all the info about my system:
OS: Ubuntu 23.04 x86_64
Host: BOM-WXX9 M1010
Kernel: 6.1.3+
[dmesg.txt](https://github.com/codepayne/linux-sound-huawei/files/13417223/dmesg.txt)
[lsmod.txt](https://github.com/codepayne/linux-sound-huawei/files/13417224/lsmod.txt)
[asound.txt](https://github.com/codepayne/linux-sound-huawei/files/13417225/asound.txt)

**Comment by codepayne** [comment]
@accelolabs As far as I can tell, the driver has loaded successfully and should work. The only issue might be in alsamixer settings.
Upload some screenshots of your alsamixer.

**Comment by accelolabs** [comment]
Sorry for wait, but here are the alsamixer screenshots - https://imgur.com/a/vZzaPDW

**Comment by accelolabs** [comment]
Ok, there was no sound because pulsaudio service was inactive despite being enabled. I started it and there was sound.

But there is some new issues with audio - loud hissing noise and speeding up. With what alsamixer settings do I fix them?

Also thanks for your awesome driver.

**Comment by codepayne** [comment]
> Ok, there was no sound because pulsaudio service was inactive despite being enabled. I started it and there was sound.
> 
> But there is some new issues with audio - loud hissing noise and speeding up. With what alsamixer settings do I fix them?
> 
> Also thanks for your awesome driver.

@accelolabs The speeding up is not clear to me yet, what I can recommend is to use chromium, which doesn't have the issue. For the hiss I'm not sure what you mean, you need to enable the same knobs as in the wiki. There is a popping sound due to the speed up, maybe that is what you hear? More details here: 
https://github.com/codepayne/linux-sound-huawei/issues/26

**Comment by accelolabs** [comment]
Nothing works, I am planning to use different OS or to resell my Huawei... That's why you check compatibility with linux beforehand.

**Comment by codepayne** [comment]
@accelolabs The sped up seems to be caused by a change in pipewire, an older version of pipewire doesn't have this issue, more details here:
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3744
