### ISSUE TITLE
no sound on huawei mate D15 laptop BOM-WXX9-PCB-B2

### ISSUE THREAD

**Issue by saber716rus** [codepayne/linux-sound-huawei#27]
Hello. I'm sorry for that post, we didn't quite understand each other. Now I'm laying it out properly. I tried ubuntu 23.10 and installed the kernel version 6.7-rc6, but there is still no sound. I upload the logs and attach the module startup config. I've archived it.

[logs.zip](https://github.com/codepayne/linux-sound-huawei/files/13725804/logs.zip)

**Comment by TomZanna** [comment]
You need to adjust your alsamixer setup.
From https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837420648
> Firstly make sure that DAC source mux is set to: LDaTA to LDAC, RDATA to RDAC. Without it there will be no sound.
> Disable Left Headphone Mixer LLIN and Right Headphone Mixer RLIN - these ones seem to add pops
> Push DAC, Headphone Mixer and Headphone to 100.

Then enable the following knobs because I see from alsa-info that they are turned off:
_Left Headphone Mixer Left DAC, Right Headphone Mixer Right DAC_


Also, at the moment a workaround is needed, read here for more: https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837502247

It could be that the sound feels accelerated, it's a known problem.

**Comment by saber716rus** [comment]
> You need to adjust your alsamixer setup. From [#26 (comment)](https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837420648)
> 
> > Firstly make sure that DAC source mux is set to: LDaTA to LDAC, RDATA to RDAC. Without it there will be no sound.
> > Disable Left Headphone Mixer LLIN and Right Headphone Mixer RLIN - these ones seem to add pops
> > Push DAC, Headphone Mixer and Headphone to 100.
> 
> Then enable the following knobs because I see from alsa-info that they are turned off: _Left Headphone Mixer Left DAC, Right Headphone Mixer Right DAC_
> 
> Also, at the moment a workaround is needed, read here for more: [#26 (comment)](https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837502247)
> 
> It could be that the sound feels accelerated, it's a known problem.

The most interesting thing is that there is no such thing in the 6.6.7 kernel.

**Comment by TomZanna** [comment]
> there is no such thing in the 6.6.7 kernel

Sorry, I assumed you were using 6.7rc. In versions prior to 6.7 the driver is not present.
If you try with 6.7rc it should work because from alsa-info I see that the correct module is loaded and there are knobs in alsa mixer.

**Comment by saber716rus** [comment]
> > there is no such thing in the 6.6.7 kernel
> 
> Sorry, I assumed you were using 6.7rc. In versions prior to 6.7 the driver is not present.
> If you try with 6.7rc it should work because from alsa-info I see that the correct module is loaded and there are knobs in alsa mixer.

I was just comparing the 2 versions. Cores. Have you recompiled the kernel?

**Comment by saber716rus** [comment]
> > there is no such thing in the 6.6.7 kernel
> 
> Sorry, I assumed you were using 6.7rc. In versions prior to 6.7 the driver is not present. If you try with 6.7rc it should work because from alsa-info I see that the correct module is loaded and there are knobs in alsa mixer.
@codepayne 
this configuration is enabled, but there is still no sound.

saber716rus@saber716rus-M1010 ~ [127]> cat /boot/config-6.7.0-060700rc6-generic | grep CONFIG_SND_SOC_AMD_ACP
CONFIG_SND_SOC_AMD_ACP=m
CONFIG_SND_SOC_AMD_ACP3x=m
CONFIG_SND_SOC_AMD_ACP5x=m
CONFIG_SND_SOC_AMD_ACP6x=m
CONFIG_SND_SOC_AMD_ACP_COMMON=m
CONFIG_SND_SOC_AMD_ACP_PDM=m
CONFIG_SND_SOC_AMD_ACP_LEGACY_COMMON=m
CONFIG_SND_SOC_AMD_ACP_I2S=m
CONFIG_SND_SOC_AMD_ACP_PCM=m
CONFIG_SND_SOC_AMD_ACP_PCI=m
saber716rus@saber716rus-M1010 ~>

**Comment by saber716rus** [comment]
@codepayne the kernel config seems to be enabled, but there is still no sound.

saber716rus@saber716rus-M1010 ~> cat /boot/config-6.7.0-060700rc6-generic | grep SOC_AMD
CONFIG_SND_SOC_AMD_ACP=m
CONFIG_SND_SOC_AMD_CZ_DA7219MX98357_MACH=m
CONFIG_SND_SOC_AMD_CZ_RT5645_MACH=m
CONFIG_SND_SOC_AMD_ST_ES8336_MACH=m
CONFIG_SND_SOC_AMD_ACP3x=m
CONFIG_SND_SOC_AMD_RV_RT5682_MACH=m
CONFIG_SND_SOC_AMD_RENOIR=m
CONFIG_SND_SOC_AMD_RENOIR_MACH=m
CONFIG_SND_SOC_AMD_ACP5x=m
CONFIG_SND_SOC_AMD_VANGOGH_MACH=m
CONFIG_SND_SOC_AMD_ACP6x=m
CONFIG_SND_SOC_AMD_YC_MACH=m
CONFIG_SND_SOC_AMD_ACP_COMMON=m
CONFIG_SND_SOC_AMD_ACP_PDM=m
CONFIG_SND_SOC_AMD_ACP_LEGACY_COMMON=m
CONFIG_SND_SOC_AMD_ACP_I2S=m
CONFIG_SND_SOC_AMD_ACP_PCM=m
CONFIG_SND_SOC_AMD_ACP_PCI=m
CONFIG_SND_SOC_AMD_MACH_COMMON=m
CONFIG_SND_SOC_AMD_LEGACY_MACH=m
CONFIG_SND_SOC_AMD_SOF_MACH=m
CONFIG_SND_SOC_AMD_RPL_ACP6x=m
CONFIG_SND_SOC_AMD_PS=m
CONFIG_SND_SOC_AMD_PS_MACH=m
saber716rus@saber716rus-M1010 ~> 


Although I did it too

  Modify /etc/modprobe.d/blacklist.conf and add the following lines:
   blacklist snd_acp3x_rn
   blacklist snd_pci_acp5x
   blacklist snd_rn_pci_acp3x

  Modify /etc/modules-load.d/modules.conf and add the following lines:
   snd_soc_es8316
   snd_acp3x_pcm_dma
   snd_acp3x_i2s 
   snd_pci_acp3x
   snd_soc_acp3x_es8336_mach

**Comment by saber716rus** [comment]
Screenshot of alsamixer
![Снимок экрана от 2023-12-20 15-00-26](https://github.com/codepayne/linux-sound-huawei/assets/22714555/959c30c7-25df-4433-8f3c-93aae80433d0)
![Снимок экрана от 2023-12-20 15-00-48](https://github.com/codepayne/linux-sound-huawei/assets/22714555/3a0935f0-1d16-44ed-b4b9-c83e525f0fef)
![Снимок экрана от 2023-12-20 15-00-55](https://github.com/codepayne/linux-sound-huawei/assets/22714555/30c7a953-6a4c-42f2-8da1-29bdd30f514c)

**Comment by saber716rus** [comment]
saber716rus@saber716rus-M1010 ~> aplay -d 1 /usr/share/sounds/alsa/Noise.wav
Воспроизведение WAVE '/usr/share/sounds/alsa/Noise.wav' : Signed 16 bit Little Endian, Частота 48000 Гц, Моно
saber716rus@saber716rus-M1010 ~>

**Comment by codepayne** [comment]
@saber716rus Why are ignoring everything that is told to you? Both the wiki and @TomZanna mentioned to you that you need to enable certain options in alsamixer. These options are not enabled in your screenshots.

Also you need to follow the instructions from the link that @TomZanna mentioned: 
https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837502247

**Comment by saber716rus** [comment]
> @saber716rus Why are ignoring everything that is told to you? Both the wiki and @TomZanna mentioned to you that you need to enable certain options in alsamixer. These options are not enabled in your screenshots.
> 
> Also you need to follow the instructions from the link that @TomZanna mentioned: 
> https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837502247
> 

Actually, I did as @TomZanna described. Wait, what did I ignore from the wiki?

**Comment by codepayne** [comment]
@saber716rus Read the wiki again, maybe you'll see it.

**Comment by saber716rus** [comment]
> @saber716rus Read the wiki again, maybe you'll see it.

Left Headphone Mixer Left DAC, Right Headphone Mixer Right DAC
  After doing these changes you should be hearing the sound.
where do they turn on? I'll check it out tomorrow.

**Comment by TomZanna** [comment]
@saber716rus go all the way to the right in alsamixer. The name is displayed in the top left corner. You have to press the M key to activate/deactivate (otherwise look at the help by pressing F1)
<img width="925" alt="image" src="https://github.com/codepayne/linux-sound-huawei/assets/43095563/4de0c549-31b5-46a5-b4db-0c042244e096">

**Comment by saber716rus** [comment]
> @saber716rus go all the way to the right in alsamixer. The name is displayed in the top left corner. You have to press the M key to activate/deactivate (otherwise look at the help by pressing F1)
> <img width="925" alt="image" src="https://github.com/codepayne/linux-sound-huawei/assets/43095563/4de0c549-31b5-46a5-b4db-0c042244e096">
> 
> 

thank you. I'll try it tomorrow.

**Comment by saber716rus** [comment]
> @saber716rus go all the way to the right in alsamixer. The name is displayed in the top left corner. You have to press the M key to activate/deactivate (otherwise look at the help by pressing F1) <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/43095563/292565187-4de0c549-31b5-46a5-b4db-0c042244e096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjU0MDgsIm5iZiI6MTcwMzMyNTEwOCwicGF0aCI6Ii80MzA5NTU2My8yOTI1NjUxODctNGRlMGM1NDktMzFiNS00NmE1LWI0ZGItMGMwNDIyNDRlMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA5NTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1M2UzYzRjYjM3ZmI1MTM3NmRiMTRiNTI2ODA2MjVjNDYyYmM5Zjg2ZTJkMmQ5NWFjNGVkMzQ5ZGMyMmZjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7DgzB0KX2INwfZ9RIstpvsPiPeFO4uWEXRoSKyLPPpo">

I turned it on and rebooted it. And there was no sound, and there is no sound.
[alsa-info.txt](https://github.com/codepayne/linux-sound-huawei/files/13758699/alsa-info.txt)

![Снимок экрана от 2023-12-23 12-51-26](https://github.com/codepayne/linux-sound-huawei/assets/22714555/f1bacf56-83aa-4714-b9b6-0d753e3c874d)

**Comment by saber716rus** [comment]
@codepayne I did, and what is the result? There is no sound anyway.

**Comment by Honda-VTEC** [comment]
Same issue on my Matebook D15 2021 Ryzen5 5500U BOM-WXX9. I've started testing the drivers on fedora 39 stable, compiling the latest 6.7rc kernel every time with the right flags but I could never get anything working. I obviously did configure alsamixer, did the workaround for the auto suspense state, but nothing. Tried even different distros: Ubuntu 23.10, 24.04, but the only way I could get some **random noises** and select "AMD ACP/ACP3x/ACP6x" as an output device was with the kernel of this repo (6.1.3).

I am currently in this situation: 

Fedora 40 Rawhide, the latest with the right flags enabled(before the 27th Dec release they weren't enabled), and out of the box I got absolutely nothing. In the audio settings I can only see Dummy output and not the "AMD ACP/ACP3x/ACP6x" output device, like for example happens on the Matebook D14. 

![Schermata del 2023-12-28 00-49-48](https://github.com/codepayne/linux-sound-huawei/assets/122612821/fa7e6899-251e-471e-a09f-f4e7fbb7b6c6)

Then I tried to configure alsamixer and did the workaround but it obviously did not work. I've tried different times to reproduce something but an error comes out: _"Broken configuration for this PCM: no configuration available"_.

![Schermata del 2023-12-27 22-56-37](https://github.com/codepayne/linux-sound-huawei/assets/122612821/d92a3e7d-241a-4c3f-a278-d4a87283db91)

![Schermata del 2023-12-29 19-33-52](https://github.com/codepayne/linux-sound-huawei/assets/122612821/38a7d175-2dd6-4bd4-b1e2-7837757fb7ad)


Recording from the microphone connected to the ES8336 chip, is also not working.

![Schermata del 2023-12-29 19-40-16](https://github.com/codepayne/linux-sound-huawei/assets/122612821/6822b890-176d-407a-a2a6-0f95835b1585)

**aplay -L**  output:

![Schermata del 2023-12-27 22-54-42](https://github.com/codepayne/linux-sound-huawei/assets/122612821/29a172fb-51c2-4b81-9207-7d09210dc5bc)

**pactl info** output:

![Schermata del 2023-12-27 21-46-16](https://github.com/codepayne/linux-sound-huawei/assets/122612821/facb9a47-894b-446c-8533-2a582c3191ca)

**lspci -vv** output:  
[lspci-vv.txt](https://github.com/codepayne/linux-sound-huawei/files/13796443/lspci-vv.txt)

**dmesg** : 

[dmesg.txt](https://github.com/codepayne/linux-sound-huawei/files/13796445/dmesg.txt)

**cat /proc/asound/cards:** 

![photo_2023-12-29_23-58-48](https://github.com/codepayne/linux-sound-huawei/assets/122612821/0c10219f-0aca-4e60-b27e-312fa0c02f97)

**Comment by codepayne** [comment]
Issue tracked in https://github.com/codepayne/linux-sound-huawei/issues/28
