### ISSUE TITLE
Sound sped-up in firefox and aplay

### ISSUE THREAD

**Issue by codepayne** [codepayne/linux-sound-huawei#29]
It seems that in more recent versions of pipewire the sound is sped-up and popping a lot in firefox and aplay.
This issue is caused by pipewire and more details can be found here:
https://github.com/codepayne/linux-sound-huawei/issues/26

This issue is for tracking the status of the issue.

**Comment by codepayne** [comment]
The sped-up problem has been fixed.
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3744

**Comment by DioEgizio** [comment]
btw, this is in pipewire 1.0.2, which recently arrived in fedora! Everything works fine now! :)
