### ISSUE TITLE
Matebook D16 AMD Ryzen 5 4600H built-in microphone not working.

### ISSUE THREAD

**Issue by nkhost** [codepayne/linux-sound-huawei#3]
After @martyn0ff commit speakers start working, but microphone not. In original ubuntu kernel 5.16 microphone works, speakers not. 

arecord -l (patched kernel)
```
**** List of CAPTURE Hardware Devices ****
card 1: amdacp3xessx833 [amd-acp3x-essx8336], device 0: ES8336 HiFi Play ES8316 HiFi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
  
arecord -l (original ubuntu 5.16)
```
**** List of CAPTURE Hardware Devices ****
card 0: acp [acp], device 0: DMIC capture dmic-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

Sound in 3.5mm jack not working too.

**Comment by codepayne** [comment]
Internal microphone (inside the laptop) also called as DMIC (Digital microphone) doesn't work with this driver due to the way AMD ACP drivers behave. With this patch only the headset microphone works.
