### ISSUE TITLE
No Sound / Random pop / noise  on Huawei MateBook 14 with Arch Linux

### ISSUE THREAD

**Issue by bandundu** [codepayne/linux-sound-huawei#32]
## Issue Description:

I am experiencing an issue with sound on my Huawei MateBook 14 (Model: KLVL-WXXW, M1010) running Arch Linux. Despite trying various fixes, I am unable to get sound output. However, mysteriously, sometimes the laptop plays sound for a split of a second, and I can recognize that there is some sort of sound coming out of the speakers. 

## System Information:

    Manufacturer: HUAWEI
    Product Name: KLVL-WXXW
    Version: M1010
    OS: Arch Linux x86_64
    Kernel: 6.7.2-arch1-1
    WM: awesome
    CPU: AMD Ryzen 5 5500U
    GPU: AMD ATI Lucienne

## Steps done
1. Installed the newest mainline kernel from official repor
2. Configured alsamixer and activated the knobs mentioned as in the wiki
3. Tried to play some music

## Attempted Workaround:

I tried the following workaround on boot without success:
echo -1 > /sys/bus/pci/drivers/snd_acp_pci/0000:03:00.5/power/autosuspend_delay_ms

## Attachments:

After boot and playing a wav with aplay [dmesg.txt](https://github.com/codepayne/linux-sound-huawei/files/14077681/dmesg.txt)

Screenshots of ALSA mixer and PulseAudio configuration

![grafik](https://github.com/codepayne/linux-sound-huawei/assets/41874924/a10d42f1-38b6-4d6b-b5f0-ac81839cee12)
![grafik](https://github.com/codepayne/linux-sound-huawei/assets/41874924/edacd785-5e0b-459a-894b-e0ec2140be8c)
![grafik](https://github.com/codepayne/linux-sound-huawei/assets/41874924/6c0e4fe7-c103-40a4-9ccd-e522d12c8d1c)
![grafik](https://github.com/codepayne/linux-sound-huawei/assets/41874924/239a722c-3606-4077-88ff-ae5ea0b4dabe)

Any insights or guidance on resolving this issue would be greatly appreciated. I've been using this laptop for more than a year now without sound :(

**Comment by fernandosang** [comment]
@bandundu Codepayne has kindly provided a near perfect kernel based on 6.8 rc1 that basically fixes all problems, except that, because of the unstable base kernel, it breaks Snap packages compatibility. If you're interested, you may wanna give that a try. Check the thread here:

https://github.com/codepayne/linux-sound-huawei/issues/30

Otherwise, if you really need Snap packages to work, you might wanna give this alternate solution a try too. For me (I have a similar laptop model) it worked pretty well, except for some random pop noises:

https://github.com/codepayne/linux-sound-huawei/issues/28#issuecomment-1878822975


I recommend you read both full threads and then figure out what works best for you. Just read everything carefully.

**Comment by bandundu** [comment]
@fernandosang Thank you for pointing me to the right direction with this. Unfortunately, that kernel is not available anymore from @codepayne 

Here's what I've done so far:

1. Installed UCM / UCM2 Configuration profiles.
2. Set up PipeWire and WirePlumber.
3. Implemented a boot service based on [this suggestion](https://github.com/codepayne/linux-sound-huawei/issues/26#issuecomment-1837502247).
4. UPDATE: Installed Kernel: 6.8.0-rc1-linux-rc had no impact at all sadly

**Observations:**

- When using terminal-based audio tools (like `aplay` for WAV files), the first audio output works, but subsequent attempts often fail.
- The typical terminal sound plays when pressing "tab" for the first time. However, repeated presses don't produce additional sounds, as if the audio device gets "blocked."
- Running `aplay` shortly after another sound has played results in an error: "Error when opening Device: The device or resource is busy".
- YouTube videos don't play properly, with occasional cracking sounds after long delays. When i mute the video, the video runs without any problems but obviously no sound

I suspect these issues might be related to codec problems or a conflict in the handling of audio streams. Attached is the [log file from PipeWire](https://github.com/codepayne/linux-sound-huawei/files/14078453/pipewire-logs.txt) for further insight.

Has anyone experienced similar issues or can offer insights into potential solutions?

![Audio Device Error](https://github.com/codepayne/linux-sound-huawei/assets/41874924/2ef8db0c-3171-462e-95b1-457510e6e681)

Thank you in advance for any assistance.

**Comment by PurestAsh** [comment]
@bandundu emm, maybe you should try ubuntu ?

I have the same Model with you.
_KLVL-WXXW 
M1010
AMD Ryzen 5 5700U
Firmware Version: 1.09_

but I use ubuntu23.10 .
the codepayne provided kernel(https://filebin.net/gnk9t9rzlvpgcacx)  is compiled from ubuntu ?
_Compiling the kernel is a bit challenging for me, and it is filled with uncertainty._
its work for me very perfect,out of box .

**Here's what I've done :**
1. install the ubuntu23.10.
2. install the codepayne provided kernel
3. install alsa-ucm-conf(in codepayne repo)
4. reboot

**Comment by bandundu** [comment]
Jesus hallelujah I finally have audio, albeit I am not sure whether this is a workaround or a solution. After running a bunch of times

`pulseaudio -k `

and with this totally killing my PulseAudio I got sound working perfectly fine! Wow, I did not expect this at all.

Sound is working for Spotify, Terminal with Aplay i would asume via ALSA, However obviously not working for apps that expect it like Firefox or discord.

On my machine I have pulseaudio 17.0 installed

Attached the PulseAudio log, I skimmed it but can not find any culprit. Can anyone help in identifying what could cause this? Would really like to understand.

[pulseaudio.log](https://github.com/codepayne/linux-sound-huawei/files/14078853/pulseaudio.log)


After deinstalling pulseaudio, installing pipewire and rebooting my system everything works like a charm now. Microphone and Speakers - just perfect

EDIT: Well mostly perfect, audio is getting sped up sometimes.

**Comment by PurestAsh** [comment]
wow ! congratulation！！

**Comment by bandundu** [comment]
@codepayne any idea what could be causing the sped up audio?

**Comment by codepayne** [comment]
> @codepayne any idea what could be causing the sped up audio?

The sped-up issue is already fixed in upstream pipewire, more details here:
https://github.com/codepayne/linux-sound-huawei/issues/29

**Comment by marchacio** [comment]
Hi everyone, 
I post the solution I found 'couse it's still useful and effective (avoiding you to waste your time researching online 😄):

https://github.com/Smoren/huawei-ubuntu-sound-fix

(Thanks a lot Smoren)
