### ISSUE TITLE
Sound card not detected on arch linux 6.8.7. Is the driver in upstream? (KLVL-WXXW M1010)

### ISSUE THREAD

**Issue by jacekjarosz55** [codepayne/linux-sound-huawei#37]
Please correct me if I'm wrong, but from what i undestand, the driver has been upstreamed and everything should work on the latest kernel, right? 
I can get https://github.com/codepayne/pop-os-linux/ to work correctly but the kernel version is really old and missing the drivers for my usb wifi adapter

I'm on KLVL-WXXW M1010 (Matebook 14 2021)

Please tell me whether I can do something to get it to work on the latest kernel, having audio on this laptop is the last thing that's really still missing for everything to work correctly

**Comment by codepayne** [comment]
Post your dmesg. This should always be posted for any kernel issue.

**Comment by jacekjarosz55** [comment]
for now i managed to install the 6.4 kernel with huawei patches from AUR (which has the wifi drivers), will upload the dmesg in a second though

**Comment by jacekjarosz55** [comment]
I have 3 kernels currently installed:
1. Stock archlinux kernel - inxi detects the device, but driver is N/A, no audio
[dmesg-stock.txt](https://github.com/codepayne/linux-sound-huawei/files/15099944/dmesg-stock.txt)
[inxi-stock.txt](https://github.com/codepayne/linux-sound-huawei/files/15099945/inxi-stock.txt)
2. 6.8.7 compiled by myself with the necessary config flags
[dmesg-custom.txt](https://github.com/codepayne/linux-sound-huawei/files/15099985/dmesg-custom.txt)
[inxi-custom.txt](https://github.com/codepayne/linux-sound-huawei/files/15099963/inxi-custom.txt)
[custom-config.txt](https://github.com/codepayne/linux-sound-huawei/files/15100010/custom-config.txt)
3. https://aur.archlinux.org/packages/linux-huawei-amd-audio
[dmesg-huawei-amd-audio.txt](https://github.com/codepayne/linux-sound-huawei/files/15100000/dmesg-huawei-amd-audio.txt)
[inxi-huawei-amd-audio.txt](https://github.com/codepayne/linux-sound-huawei/files/15099998/inxi-huawei-amd-audio.txt)

**Comment by jacekjarosz55** [comment]
Noticed that my custom kernel is missing the snd_pci_acp3x_es8336_mach module:
 modprobe: FATAL: Module snd_pci_acp3x_es8336_mach not found in directory /lib/modules/6.8.7scare
 
 I'll try compiling it again, since i might have the comment in the config wrong
 UPDATE: the module is still missing, although snd_soc_acp_es8336_mach exists. either way, the speaker doesn't get detected by it at all

**Comment by jacekjarosz55** [comment]
Found this error in dmesg (on the compiled 6.8.7)
[    8.543545] snd_acp_pci 0000:03:00.5: enabling device (0000 -> 0002)
[    8.543925] snd_acp_pci 0000:03:00.5: Runtime PM usage count underflow!
[    8.543929] snd_acp_pci: probe of 0000:03:00.5 failed with error -22

Which makes me believe this is a duplicate of #35 . this issue can probably be closed

**Comment by codepayne** [comment]
This problem is a regression done by AMD dev, specifically this commit: 
https://github.com/torvalds/linux/commit/4af565de9f8c74b9f6035924ce0d40adec211246

It was also fixed by that AMD dev later on:
https://github.com/torvalds/linux/commit/09068d624c490c0e89f33f963c402f1859964467

The fix should reach stable linux 6.8.9
