### ISSUE TITLE
For a total newcomer to kernel compiling - basic instructions

### ISSUE THREAD

**Issue by andreaconsole** [codepayne/linux-sound-huawei#4]
First of all, thank you very much for sharing this solution to an annoying problem that Huawei decided not to solve.
I've never done this before, but while I'm waiting (too long) for an official solution, I'd like to give it a try.
I just need to download everything to a local folder and follow one of the many guides for compiling and installing the kernel, right?
Is there anything else I should know before complaining?

**Comment by codepayne** [comment]
Nothing too special :)  clone the master branch, create the config file, add the mentioned kernel config options,  compile the kernel, deploy it, update the bootloader, modify the mentioned files, and then use alsamixer. After that you should hear the sound.

**Comment by martyn0ff** [comment]
@andreaconsole I would suggest to follow Arch Linux wiki: https://wiki.archlinux.org/title/Kernel/Traditional_compilation, they have straightforward instructions to follow.

**Comment by andreaconsole** [comment]
@martyn0ff thank you, that guide looks both complete and easy to follow. However, as I have a 5500u ( which seems to be not completely supported yet), I will stay "at the window" some more time.

**Comment by takry** [comment]
I did everything as it is written in the guide. Alsamixer does not see the required amd-acp3x-essx8336. Matebook Ryzen 5 5500u  2021.

**Comment by takry** [comment]
Here's lsmod | grep snd_ :

`snd_sof_amd_renoir     16384  0
snd_sof_amd_acp        49152  1 snd_sof_amd_renoir
snd_sof_pci            24576  1 snd_sof_amd_renoir
snd_sof               262144  2 snd_sof_amd_acp,snd_sof_pci
snd_sof_utils          20480  1 snd_sof
snd_hda_codec_hdmi     81920  1
snd_rpl_pci_acp6x      20480  0
snd_hda_intel          53248  1
snd_acp_pci            16384  0
snd_intel_dspcfg       36864  2 snd_hda_intel,snd_sof
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_acp3x_i2s          16384  0
snd_acp_config         16384  2 snd_acp_pci,snd_sof_amd_renoir
snd_soc_acpi           16384  2 snd_sof_amd_acp,snd_acp_config
snd_hda_codec         172032  2 snd_hda_codec_hdmi,snd_hda_intel
snd_acp3x_pcm_dma      16384  0
snd_pci_acp6x          20480  0
snd_hda_core          114688  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
snd_pci_acp3x          20480  0
snd_hwdep              20480  1 snd_hda_codec
snd_soc_es8316         49152  0
snd_soc_es83xx_dsm_common    24576  1 snd_soc_es8316
snd_soc_core          364544  4 snd_acp3x_pcm_dma,snd_acp3x_i2s,snd_sof,snd_soc_es8316
snd_compress           24576  1 snd_soc_core
ac97_bus               16384  1 snd_soc_core
snd_pcm_dmaengine      20480  1 snd_soc_core
snd_pcm               155648  13 snd_acp3x_pcm_dma,snd_sof_amd_acp,snd_hda_codec_hdmi,snd_pci_acp6x,snd_hda_intel,snd_hda_codec,snd_sof,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_es8316,snd_hda_core,snd_pcm_dmaengine
snd_seq_midi           20480  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            45056  1 snd_seq_midi
snd_seq                77824  2 snd_seq_midi,snd_seq_midi_event
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
snd_timer              40960  2 snd_seq,snd_pcm
snd                   114688  14 snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi

`

**Comment by codepayne** [comment]
@takry open a new issue for your problem, also upload output from dmesg command

**Comment by thekirici** [comment]
Matebook 14 Ryzen 5 5500U installation cannot be done. It gives some errors during installation.

**Comment by thekirici** [comment]
@martyn0ff when I did everything here and rebooted. It doesn't show as kernel 6.1.3. What did i miss?
https://wiki.archlinux.org/title/Kernel/Traditional_compilation

**Comment by martyn0ff** [comment]
@thekirici Did you select your custom compiled kernel in GRUB? If you compiled it successfully it can be found in "Advanced options for Arch Linux" (at least that's what the menu item is called in my case)

**Comment by thekirici** [comment]
@martyn0ff I did everything as shown in the tutorial without any error. But 4.3 Make initial RAM disk, gives error:   mkinitcpio: command not found. 
When I skip this process and restart. I can't see kernel 6.1.3 in GRUB. There's only 5.1.9 out there.
