### ISSUE TITLE
Huawei MateBook 14 AMD 2021 no sound with patched kernel

### ISSUE THREAD

**Issue by Alexey336** [codepayne/linux-sound-huawei#8]
First of all big thanks for your work. It seems like driver was loaded. I can change the volume level, I configured alsamixer the way wiki says but still can't hear anything

There is also no way to enable `Left Headphone Mixer Left DAC` and `Right Headphone Mixer Right DAC` in alsamixer

```
OS: Fedora Linux 37 (KDE Plasma) x86_64
Host: KLVL-WXXW M1010
Kernel: 6.1.3+
CPU: AMD Ryzen 5 5500U with Radeon Graphics
```

```
[aleksey@fedora ~]$ lsmod | grep snd_
snd_seq_dummy          16384  0
snd_hrtimer            16384  1
snd_seq                90112  7 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
snd_sof_amd_renoir     16384  0
snd_sof_amd_acp        45056  1 snd_sof_amd_renoir
snd_hda_codec_hdmi     77824  1
snd_sof_pci            24576  1 snd_sof_amd_renoir
snd_hda_intel          53248  2
snd_sof               266240  2 snd_sof_amd_acp,snd_sof_pci
snd_sof_utils          20480  1 snd_sof
snd_hda_codec         147456  2 snd_hda_codec_hdmi,snd_hda_intel
snd_acp_config         16384  1 snd_sof_amd_renoir
snd_soc_acpi           16384  2 snd_sof_amd_acp,snd_acp_config
snd_intel_dspcfg       32768  2 snd_hda_intel,snd_sof
snd_hda_core           90112  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_hwdep              16384  1 snd_hda_codec
snd_rpl_pci_acp6x      20480  0
snd_pci_acp6x          20480  0
snd_soc_es8316         49152  1
snd_soc_es83xx_dsm_common    24576  1 snd_soc_es8316
snd_soc_acp3x_es8336_mach    20480  3
snd_pci_acp3x          20480  0
snd_acp3x_i2s          16384  1
snd_acp3x_pcm_dma      16384  1
snd_soc_core          307200  5 snd_acp3x_pcm_dma,snd_acp3x_i2s,snd_sof,snd_soc_es8316,snd_soc_acp3x_es8336_mach
snd_compress           28672  1 snd_soc_core
ac97_bus               16384  1 snd_soc_core
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pcm               131072  15 snd_acp3x_pcm_dma,snd_sof_amd_acp,snd_hda_codec_hdmi,snd_pci_acp6x,snd_hda_intel,snd_hda_codec,snd_sof,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_es8316,snd_hda_core,snd_soc_acp3x_es8336_mach,snd_pcm_dmaengine
snd_timer              45056  3 snd_seq,snd_hrtimer,snd_pcm
snd                   106496  23 snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_soc_acp3x_es8336_mach
```

[acpidump.zip](https://github.com/codepayne/linux-sound-huawei/files/10530806/acpidump.zip)
[modalias.txt](https://github.com/codepayne/linux-sound-huawei/files/10530807/modalias.txt)
[dmidecode.txt](https://github.com/codepayne/linux-sound-huawei/files/10530808/dmidecode.txt)
[cpuinfo.txt](https://github.com/codepayne/linux-sound-huawei/files/10530809/cpuinfo.txt)

**Comment by codepayne** [comment]
Also upload the output from dmesg command.

**Comment by Alexey336** [comment]
[dmesg.txt](https://github.com/codepayne/linux-sound-huawei/files/10560919/dmesg.txt)

**Comment by codepayne** [comment]
I don't see anything wrong in the kernel logs, seems the driver loaded fine. 
Please run the command `alsa-info` and attach the output here.

**Comment by Alexey336** [comment]
[alsa-info.txt](https://github.com/codepayne/linux-sound-huawei/files/10611117/alsa-info.txt)

**Comment by codepayne** [comment]
> There is also no way to enable `Left Headphone Mixer Left DAC` and `Right Headphone Mixer Right DAC` in alsamixer
> 

Looking in the alsa-info output there are 3 issues:
- The Headphone Mixer knob is zero, it should be increased, just set it at max
- Left Headphone Mixer Left DAC is not enabled
- Right Headphone Mixer Right DAC is not enabled

Now you said that you can't enable `Left Headphone Mixer Left DAC` and `Right Headphone Mixer Right DAC` how did you try to enable them in alsamixer?

**Comment by Alexey336** [comment]
It's just inactive in alsamixer, I can't switch it. Same for Right Headphone Mixer Right DAC

![image](https://user-images.githubusercontent.com/9166661/216825380-7fdeaa92-5ab3-4490-95ac-900853795e37.png)

**Comment by codepayne** [comment]
how are you activating these switches, what buttons are you pressing?

**Comment by Alexey336** [comment]
I tried with space, enter and arrow buttons

**Comment by Alexey336** [comment]
Lol I just found that these sliders enables with M button and sound now works

**Comment by Alexey336** [comment]
What else I can change in alsamixer to make sound louder?
