### ISSUE TITLE
Alsamixer does not see the required amd-acp3x-essx8336. Matebook Ryzen 5 5500u 2021.

### ISSUE THREAD

**Issue by takry** [codepayne/linux-sound-huawei#9]
I did everything as it is written in the guide. Alsamixer does not see the required amd-acp3x-essx8336. Matebook Ryzen 5 5500u 2021.
dmesg:
[2.pdf](https://github.com/codepayne/linux-sound-huawei/files/10548687/2.pdf)

**Comment by codepayne** [comment]
From what I see in dmesg output the driver `snd_soc_acp3x_es8336_mach` is not loaded. You'll have to check why it isn't loaded, also you can try to load it manually.

**Comment by takry** [comment]
Ok, how i can download it manually? I'm newbie with Ubuntu.

**Comment by codepayne** [comment]
you'll have to investigate yourself how to do these things, there are a million websites explaining how to work with kernel modules.
